import type {Metadata, Viewport} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import Script from "next/script";

const inter = Inter({subsets: ["latin"], variable: "--font-sans"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
    viewportFit: 'cover',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
        <Script strategy="beforeInteractive" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJv7lkKemUFD_ovIk1G5WEmRlwtdPMC9M&libraries=geometry" />
        </head>
        <body className={cn(
            'min-h-dvh bg-background font-sans antialiased',
            inter.variable,
        )}>
        <main vaul-drawer-wrapper="">
            {children}
        </main>
        </body>
        </html>
    );
}
